// Generate a TypeScript .d.ts file describing the typed client surface from
// an action manifest. The generated file imports from "@ageniti/core/client"
// for the runtime and gives users autocomplete + type-checking for every
// action input and output.
//
// We do JSON Schema → TS Type via a minimal converter that handles the shapes
// our schema layer produces. For exotic schemas (deep unions, recursion), we
// degrade to `unknown` rather than emit broken TS.

import { createActionManifest } from "../runtime/core.js";

export function generateClientTypes(actions, options = {}) {
  const manifest = createActionManifest(actions);
  const interfaceName = options.interfaceName ?? "AgenitiClient";
  const importFrom = options.importFrom ?? "@ageniti/core/client";

  const lines = [
    "// Auto-generated by @ageniti/core. Do not edit by hand.",
    `// Generated at: ${new Date().toISOString()}`,
    "",
    `import type { AgenitiClientError, RuntimeResult } from "${importFrom}";`,
    "",
    "export interface InvokeOptions {",
    "  signal?: AbortSignal;",
    "  idempotencyKey?: string;",
    "  timeoutMs?: number;",
    "  confirm?: boolean;",
    "  metadata?: Record<string, unknown>;",
    "}",
    "",
    "export interface RawInvokeOptions extends InvokeOptions {",
    "  raw: true;",
    "}",
    "",
    `export interface ${interfaceName} {`,
  ];

  for (const action of manifest) {
    const inputType = jsonSchemaToTs(action.inputSchema, 1) ?? "unknown";
    const outputType = action.outputSchema ? jsonSchemaToTs(action.outputSchema, 1) : "unknown";
    const description = action.description?.trim();
    const docLines = [];
    if (description) {
      docLines.push(`  /** ${description.replace(/\*\//g, "*\\/")} */`);
    }
    if (action.deprecated) {
      docLines.push(`  /** @deprecated ${action.deprecation?.message ?? ""} */`);
    }

    // Two overloads: with `raw: true` the call resolves to the full envelope,
    // otherwise it resolves to the validated `data` (or throws AgenitiClientError).
    for (const doc of docLines) lines.push(doc);
    lines.push(`  ${action.name}(input: ${inputType}, options: RawInvokeOptions): Promise<RuntimeResult<${outputType}>>;`);
    for (const doc of docLines) lines.push(doc);
    lines.push(`  ${action.name}(input: ${inputType}, options?: InvokeOptions): Promise<${outputType}>;`);
  }

  lines.push("");
  lines.push(`  $invoke<T = unknown>(name: string, input: unknown, options: RawInvokeOptions): Promise<RuntimeResult<T>>;`);
  lines.push(`  $invoke<T = unknown>(name: string, input: unknown, options?: InvokeOptions): Promise<T>;`);
  lines.push(`}`);
  lines.push("");
  lines.push(`export { AgenitiClientError };`);
  lines.push(`export type { RuntimeResult };`);

  return lines.join("\n");
}

export function jsonSchemaToTs(schema, indent = 0) {
  if (!schema || typeof schema !== "object") return "unknown";

  if (schema.const !== undefined) return JSON.stringify(schema.const);
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (schema.anyOf) return schema.anyOf.map((s) => jsonSchemaToTs(s, indent)).join(" | ") || "unknown";
  if (schema.oneOf) return schema.oneOf.map((s) => jsonSchemaToTs(s, indent)).join(" | ") || "unknown";
  if (schema.allOf) return schema.allOf.map((s) => jsonSchemaToTs(s, indent)).join(" & ") || "unknown";

  const t = schema.type;
  if (t === "string") return "string";
  if (t === "number" || t === "integer") return "number";
  if (t === "boolean") return "boolean";
  if (t === "null") return "null";

  if (t === "array") {
    const itemType = schema.items ? jsonSchemaToTs(Array.isArray(schema.items) ? schema.items[0] : schema.items, indent) : "unknown";
    return `Array<${itemType}>`;
  }

  if (t === "object" || schema.properties) {
    const properties = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const propLines = [];
    const pad = "  ".repeat(indent + 1);

    for (const [key, value] of Object.entries(properties)) {
      const optional = !required.has(key) ? "?" : "";
      const propType = jsonSchemaToTs(value, indent + 1);
      const safeKey = /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
      propLines.push(`${pad}${safeKey}${optional}: ${propType};`);
    }

    if (schema.additionalProperties && schema.additionalProperties !== false) {
      const valueType = typeof schema.additionalProperties === "object"
        ? jsonSchemaToTs(schema.additionalProperties, indent + 1)
        : "unknown";
      propLines.push(`${pad}[key: string]: ${valueType};`);
    }

    if (propLines.length === 0) return "Record<string, unknown>";
    return `{\n${propLines.join("\n")}\n${"  ".repeat(indent)}}`;
  }

  return "unknown";
}
